pipeline {
  agent {
    label 'docker-agent'
  }

  tools {
    nodejs '18.6.0'
  }

  stages {
    stage('Build') {
      steps {
        echo 'Installing'
        sh 'npm install ./frontend'
        echo 'Building'
        sh 'npm build ./frontend'
        sh 'npm install @angular/cli'
        sh 'pushd frontend && ng build && popd'
      }
    }
    stage('Deploy') {
      when {
        expression {
          currentBuild.result == null || currentBuild.result == 'SUCCESS'
        }
      }
      environment {
        ACCESS_KEY = credentials('raspberry-pi-ssh')
      }
      steps {
        echo 'Deploying'
        sh 'printenv'
        sh('scp ./frontend/dist/mfb-frontend/* pi:$ACCESS_KEY@192.168.0.24:/tmp')
      }
    }
  }
}
