services:
  mfb-config:
    container_name: mfb-config
    privileged: true
    hostname: mfb-config
    image: aabdeen/mfb-config:0.0.1-SNAPSHOT
    expose:
      - "8787"
    ports:
      - "8787:8787"
    environment:
      SPRING_PROFILES_ACTIVE: basic,offline
      MFB_CONF_DIR: /opt/mfb/conf
    volumes:
      - type: bind
        source: /opt/mfb/conf
        target: /opt/mfb/conf
    networks:
      - mfb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/mfb-rest/docker"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s
  mfb-rest:
    container_name: mfb-rest
    privileged: true
    hostname: mfb-rest
    image: aabdeen/mfb-rest:0.0.1-SNAPSHOT
    expose:
      - "8387"
    ports:
      - "8387:8387"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: docker 
      MFB_HOME: /opt/mfb
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      spring.config.import: "configserver:http://mfb-config:8787"
    volumes:
      - type: bind
        source: /opt/mfb
        target: /opt/mfb
      - type: bind
        source: /media/ahmedhillawi
        target: /media/ahmedhillawi
      - type: bind
        source: /run/user/1000/gvfs/mtp\:host\=OnePlus_OnePlus_845cade8/Internal\ shared\ storage/DCIM/Camera
        target: /opt/mfb/device/6t/img
    networks:
      - mfb-network
    depends_on:
      - mfb-config
    restart: on-failure
  mfb-frontend:
    container_name: mfb-frontend
    image: aabdeen/mfb-frontend:0.0.1-SNAPSHOT
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
networks:
  mfb-network:
    name: mfb-network
    driver: bridge
    external: true
