services:
  mfb-backend:
    container_name: mfb-backend
    privileged: true
    image: hillawi/mfb-backend:1.0.0
    ports:
      - "8387:8387"
    volumes:
      - /media:/media
      - /opt/mfb/udev:/opt/mfb/udev