= Media Files Backup (MFB)

Backup your pictures and videos files in an easy and fast way.

== General information

The media files (images and videos) should respect the following naming convention:

* [IMG|VID]_YYYYMMDD.[jpg|mp4]

Where:

* *YYYY* the year
* *DD* the month
* *MM* the day

This is usually the case for digital cameras and phones.

== Installation and Getting Started

=== Backup your files using the script

* Add the environment variables (see con/env.conf)
* Mount the input and output end points (see conf/devices.conf)
* Run the script (launch_backup.sh) with the following arguments:
- The device ID (encoded earlier in conf/devices.conf)
- The media type (IMG or VID)

----
$MFB_BIN_DIR/launch_backup.sh 6t IMG
----

=== Backup your files automatically
This feature uses udev. The idea is to launch the backup process as soon as
a source device (type=source) and a target (type=target) devices are connected.

1. You need to find your device ID and add it to conf/udev-mfb.rules
  a. For USB devices

    pi@raspberrypi:~ $ udevadm info /dev/sda1 | grep ID_FS_UUID
    E: ID_FS_UUID=9C2A-D57B
    E: ID_FS_UUID_ENC=9C2A-D57B

  b. For OTP devices

    $MFB_BIN_DIR/launch_backup.sh 6t IMG

=== Backup your files using the Frontend

* Start the backend (server.js - requires Node.js) in the same machine where the scripts are installed
* Start the fronted (ng serve or ng build and deploy)
* An example of nginx configuration is provided if needed (see conf/nginx-mfb.conf)

=== Sequence Diagrams

==== Using the Frontend

```mermaid
sequenceDiagram
    ACTOR john as John Doe
    participant front as Frontend
    participant rest as REST API
    participant bash as SYSTEM SCRIPT
    participant config as CONFIGURATION
    john->>+front: Access the home page
    front->>+rest: Get devices
    rest->>config: Read configurations
    rest-->>-front: Devices list
    front->>-john: Show the devices list
    john->>+front: Launch backup
    front->>+rest: Backup files
    rest->>+bash: Backup files
    bash->>config: Read configurations
    bash->>bash: Do backup
    bash->>-rest: Files backed up
    rest->>-front: Files backed up
    front->>-john: Backup done
```