apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mfb-config
  name: mfb-config
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mfb-config
  template:
    metadata:
      labels:
        app: mfb-config
        domain: mfb
        tier: backend
    spec:
      containers:
      - name: mfb-config
        image: aabdeen/mfb-config:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: port-8787
          containerPort: 8787
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: basic,offline
        - name: MFB_CONF_DIR
          value: /opt/mfb/conf
        volumeMounts:
        - name: conf-volume
          mountPath: /opt/mfb/conf
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /actuator/health/liveness
            port: 8787
            scheme: HTTP 
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /actuator/health/readiness
            port: 8787
            scheme: HTTP
      volumes:
      - name: conf-volume
        hostPath:
          path: /opt/mfb/conf
