apiVersion: v1
kind: Service
metadata:
  labels:
    app: mfb-rest
    domain: mfb
  name: mfb-rest
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 8387
  selector:
    app: mfb-rest
status:
  loadBalancer: {}
