apiVersion: v1
kind: Service
metadata:
  labels:
    app: mfb-frontend
    domain: mfb
  name: mfb-frontend
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 8383
  selector:
    app: mfb-frontend
status:
  loadBalancer: {}
